run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gosimple:
    checks: ["-all"]

linters:
  disable-all: true
  enable:
    - gosimple

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: ".*"
      linters:
        - gosimple
