run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  typecheck:
    enabled: false
  govet:
    enabled: false

linters:
  disable-all: true
  enable:
    - gosimple
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
