linter-options:
  timeout: 5m

linters:
  disable:
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - govet
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
